### ISSUE TITLE
java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()

### ISSUE THREAD

**Issue by Emalton** [webbukkit/Dynmap-Citizens2#4]
I got the following error while trying to run Dynmap-Citizens2 on Spigot 1.10.

[18:20:53] [Craft Scheduler Thread - 2/WARN]: org.apache.commons.lang.UnhandledException: Plugin Dynmap-Citizens2 v0.20 generated an exception while executing task 442
at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: org.bukkit.Server.getOnlinePlayers()[Lorg/bukkit/entity/Player;
at us.dynmap.citizens2.MetricsLite.postPlugin(MetricsLite.java:273)
at us.dynmap.citizens2.MetricsLite.access$300(MetricsLite.java:50)
at us.dynmap.citizens2.MetricsLite$1.run(MetricsLite.java:165)
at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
... 3 more

If anymore information is needed, please let me know!

**Comment by mikeprimm** [comment]
Just release v0.30 on dev.bukkit.org - give it a try
